
[meta]
build_root = "/opt/rupert/build_root"

[[repos]]
integration = "bitbucket"
owner = "superman"
reponame = "linux"
api_token = "banana-crepes"
build_instruction = { steps = [
      {cmd = "make"},
      {cmd = "make test"},
    ]}
